# Generated by Django 3.1.1 on 2020-09-28 02:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CastMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Cast member name')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(verbose_name='Chapter number')),
                ('title', models.TextField(verbose_name='Episode title')),
                ('subtitle_filename', models.TextField(verbose_name='Episode subtitle file name')),
                ('raw_captions', models.TextField(verbose_name='Raw caption contents')),
            ],
        ),
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(verbose_name='Line length in time')),
                ('start', models.DurationField(verbose_name='Line start timestamp')),
                ('end', models.DurationField(verbose_name='Line end timestamp')),
                ('text', models.TextField(verbose_name='Caption text')),
                ('lines', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='episodes.episode')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='episodes.castmember')),
            ],
        ),
    ]
